### ISSUE TITLE
Array.prototype.fill optimisation

### ISSUE THREAD

**Issue by nagayev** [bellard/quickjs#1]
My code:
`var a = new Array(10**9); a=a.fill(0);`
So I suggest:

    Add memory limit e.g 2GB RAM
    Add optimization for such arrays (like PHP Immutable arrays)

`$a=array(); for($i=0;$i<1000000;$i++) $a[$i]=array("hello") memory_get_usage(true) //about 34mb`

**Comment by bellard** [comment]
You can enable memory limitation with the --memory-limit qjs option. Optimizing such arrays adds complexity in the engine for little benefits.

**Comment by nagayev** [comment]
@bellard Okey, thanks.
