### ISSUE TITLE
Advice:Can it complied by msvc complier?

### ISSUE THREAD

**Issue by ScSofts** [bellard/quickjs#10]
I tried many times ,but it always failed.I have studied the source code for a long time.There are too many GCC futures used in this project.Please help me.Thanks

**Comment by X-Ryl669** [comment]
It seems like it's possible, check https://github.com/c-smile/quickjs/ 
Unfortunately, there isn't any link anymore to the fork network for this project.

**Comment by stevefan1999-personal** [comment]
Yes. But you will need to use Clang-Cl backend instead. The biggest issue is that QuickJS uses GNU C extensions where it simply isn't even recognizable by MSVC. On the other hand the Clang-CL frontend has a Unix heritage and thus this is supported. The MSVC backend will still generate efficient code for Windows.

**Comment by bellard** [comment]
You should look at the current version where reliance on gcc extensions has been reduces.

**Comment by stevefan1999-personal** [comment]
@bellard yet something like attributes are still not gonna happen in MSVC and we must use clang-cl for a set back in that case

**Comment by X-Ryl669** [comment]
By grepping the code, there isn't so many attribute used and most of them are behind macro that can be "platform" specialized. There's only few places where there is still some `attribute(printf)` but that's probably easily fixable in half an hour.

**Comment by ScSofts** [comment]
OK Thanks
