### ISSUE TITLE
delete a?.b does not take effect

### ISSUE THREAD

**Issue by chemwolf6922** [bellard/quickjs#103]

**Comment by chemwolf6922** [comment]
test code
```Javascript
let a = {b:true};
delete a?.b;
console.log(JSON.stringify(a));
```
outputs:
```
{"b":true}
```
Run this code with node, and the output will be:
```
{}
```

**Comment by chemwolf6922** [comment]
The use case for this will be 
```
delete a.b?.c;
```
where a.b may not exist.

**Comment by mstepin** [comment]
This should definitely be fixed. Optional chaining, as part of ECMA2020, must also work for 'delete'.

**Comment by bellard** [comment]
fixed
