### ISSUE TITLE
the bytecode compile looks a little unstable

### ISSUE THREAD

**Issue by JiuniangYZ** [bellard/quickjs#104]
I am using quickJS with emscripten to build in-browser JS runtime for 3rd party users and gaining pretty good acceleration for boot by the usage of bytecode compile funtionality. while it looks like that some very small change(such as adding or removing another \n, or any other meaningless char at the tail) could cause the compile fail. It will be deeply appreciated if anyone could provide some suggestion to make it stabler. THX

**Comment by swankjesse** [comment]
If you omit debug symbols then your compiled bytecode won’t have line number information in it. That might be what’s causing different compiles of code that only differ by whitespace to differ in output.
