### ISSUE TITLE
A bug of number parse and stringify  when locale settings is special

### ISSUE THREAD

**Issue by TwinKleS-C** [bellard/quickjs#106]
VERSION: quickjs 2021-03-27
OS: Win11-21H2-ZHCN and Win10-21H2-RUSSIAN

I use quickjs to run javascript in my program, but my user report a problem.
When I change the number point as comma, quickjs can't parse and stringify float correctly, but in some countries（like russia），the default number point of windows PC is comma.
for example:
![22-01_13-02-48-05_Snipper - Snipaste](https://user-images.githubusercontent.com/37923060/149216894-32001271-7dce-46a1-b899-547138d7c539.png)
I found the reason on "quickjs.c"
"strtod" will called on "js_strtod",  "snprintf" will called on "js_fcvt1", when parse or stringify a Number object, js_strtod and js_fcvt1 will be called. , strtod and snprintf will use comma be a number point when system number point is comma
![22-01_13-04-02-12_core - Microsoft Visual Studio](https://user-images.githubusercontent.com/37923060/149217623-280eb500-d9af-41a7-8357-dfbe166b74b3.png)
![22-01_13-04-05-24_core - Microsoft Visual Studio](https://user-images.githubusercontent.com/37923060/149217639-58804e0d-b6bb-4e9b-a0c1-455794994070.png)

I hope this bug can be fixed

**Comment by denizsokmen** [comment]
Hi @bellard , if I am reading this correctly, the following commit must've fixed this behavior and made QuickJS locale-agnostic recently: https://github.com/bellard/quickjs/commit/993660621a0a834c93eaad68713b2dc25508b326

Is that correct?

**Comment by bellard** [comment]
Yes, it is fixed.
