### ISSUE TITLE
Promise and await problem

### ISSUE THREAD

**Issue by AndyGuoPLZ** [bellard/quickjs#128]
it seems there are some issues in Promise and Await synax:
eg:jsContext.executeVoidScript("console.log(\"Hello World\");\n" +
                                "function testAsync(params) {\n" +
                                "    console.log(\"test Async start\");\n" +
                                "    return new Promise(function (resolve, reject) {\n" +
                                "        resolve(\"done\");\n" +
                                "    });\n" +
                                "}\n" +
                                "\n" +
                                "async function main(){\n" +
                                "    var t = await testAsync(11);\n" +
                                "    console.log(\"test finish\"+t);\n" +
                                "}\n" +
                                "main();",null);
The log in console only shows Hello world and test Async start 
And the "test finish" has been gone and it seems it has been blocked at the  line "  var t = await testAsync(11);\n" +"

**Comment by andrewrch** [comment]
You need to run the tasks on the job queue. See:

``JS_EnqueueJob()``, ``JS_IsJobPending()``,
``JS_ExecutePendingJob()``

**Comment by anuragvohraec** [comment]
> You need to run the tasks on the job queue. See:
> 
> `JS_EnqueueJob()`, `JS_IsJobPending()`, `JS_ExecutePendingJob()`

And when should they be called , right before closing run time ?

**Comment by markand** [comment]
Anyone has an example to share? I'm currently trying to work with promises from C and the documentation is pretty lackluster. No worry, I'd love to contribute an example but for that I need to understand how the job function pointer should look like in JS_EnqueueJob and how JS_ExecutePendingJob supposed to be called.
