### ISSUE TITLE
Why is linux x86_64 binary release qjs executable 915.5KB, compiled from source 5.3MB?

### ISSUE THREAD

**Issue by guest271314** [bellard/quickjs#136]
The `qjs` executable from [quickjs-linux-x86_64-2021-03-27.zip](https://bellard.org/quickjs/binary_releases/quickjs-linux-x86_64-2021-03-27.zip) is 915.5KB.

The `qjs` executable produced by the following is 5.3MB. Why?

```
git clone https://github.com/bellard/quickjs.git
cd quickjs
make
```

**Comment by nesbox** [comment]
> The qjs executable produced by the following is 5.3MB. Why?

Perhaps you build it with debug info, try to add `-O2` option to the compiler.

**Comment by guest271314** [comment]
Where do I do that?

**Comment by suchangv** [comment]
Maybe you should use strip ./qjs

**Comment by guest271314** [comment]
> Maybe you should use strip ./qjs

Kindly explain in detail.
