### ISSUE TITLE
Promise's then is not called

### ISSUE THREAD

**Issue by anuragvohraec** [bellard/quickjs#140]
I have been playing with quickjs and libuv.
I am using the core JSRuntime , without the qjs and the std modules.

I am able to implement `console.log` and `setTimeout` (using libuv) method. However finding difficulty with promise chaining.
```js
let b =5;
setTimeout(()=>{
    console.log('T1 ran');
    
},5000);

// console.log("End");
let b =5;
new Promise(res=>{
    console.log("Inside promise. Closure:",b);
    setTimeout(()=>{
        console.log("Called inside promise timeout.Closure:",b);
        res("Promise resolved");
    },1000);
}).then(e=>{
    console.log(e);
})

```
A JS script like this will evaluate to :
```
Inside promise. Closure: 5
Called inside promise timeout.Closure: 5
T1 ran
```
It never prints `Promise resolved`.  

What could be wrong ?

**Comment by anuragvohraec** [comment]
Ok resolved the issue. The slution to thsi problem is quoted [here](https://github.com/bellard/quickjs/issues/128#issuecomment-1240336470).
>You need to run the tasks on the job queue. See:
```
JS_EnqueueJob(), JS_IsJobPending(),
JS_ExecutePendingJob()
```

**Comment by saghul** [comment]
In case it helps I've done a QuickJS + libuv runtime here: https://github.com/saghul/txiki.js
