### ISSUE TITLE
how to get a smaller build ?

### ISSUE THREAD

**Issue by anuragvohraec** [bellard/quickjs#141]
Hi,
The official doc claims to have smaller build ` 210 KiB of x86 code for a simple hello world program`.
However when I  run simply `make`, the `qjs` comes to be around **5.4MB**.
Do I need to pass any flags while building to have smaller build ?

**Comment by heyheyhello** [comment]
https://github.com/bellard/quickjs/issues/136

**Comment by anuragvohraec** [comment]
> #136

By add the `O3 flags`, I was able to bring it to 1.4 mb. Still its not 210KB.

**Comment by heyheyhello** [comment]
Are you using `strip` as #136 says? Try `strip -v yourbinary` and see the output.

**Comment by anuragvohraec** [comment]
> Are you using `strip` as #136 says? Try `strip -v yourbinary` and see the output.

Yes tried that too, it gives 1MB output.

**Comment by saghul** [comment]
Are you building with big num support? That added a bit too.

**Comment by anuragvohraec** [comment]
> Are you building with big num support? That added a bit too.

Yes done that. Not much of a difference in the build outcome for me.

**Comment by anuragvohraec** [comment]
> Are you using `strip` as #136 says? Try `strip -v yourbinary` and see the output.

Ok so after removing big num and strippng it, the binary I get is somewhere around 950 KB. However I get error message when building my dependent code: 
`archive has no index; run ranlib to add one`

**Comment by anuragvohraec** [comment]
I am closing this issue. The official `qjs` is of somewhere arround 950KB, and my code came out as Around 1MB not much of a difference.
Thank your for helping, quickjs community.
