### ISSUE TITLE
whats up with magic ?

### ISSUE THREAD

**Issue by anuragvohraec** [bellard/quickjs#142]
Hi All,

I see many quickjs functions and structs have an argument/property `magic` in it. What does it mean and does in general ?

**Comment by saghul** [comment]
It's a way to simplify some functions that would otherwise have 99% of the code duplicated.

If you look at the read and write functions you'll see one gets a magic of 0, the other a magic of 1, and this used internally to call the right function, but this way the implementation is shared.

**Comment by anuragvohraec** [comment]
> It's a way to simplify some functions that would otherwise have 99% of the code duplicated.

thanks
