### ISSUE TITLE
Symbol stringification

### ISSUE THREAD

**Issue by mitsuhiko** [bellard/quickjs#149]
There is a currently some inconsistency with how symbols are handled between the public C API (eg: `JS_ToCStringLen2`) and `toString` on the JS side. A symbol on the JavaScript side can be stringified by calling `toString()` on it, on the C side an error is produced:

```
TypeError: cannot convert symbol to string
```

This is created by `JS_ToStringInternal`, yet `js_symbol_toString` claims that it wants to use the former:

```c
/* XXX: use JS_ToStringInternal() with a flags */
```

I'm not sure what the current logic is, but it seems odd that the JS can stringify symbols and the C side can not.

**Comment by bellard** [comment]
This is the expected behavior. JS_ToCString() is equivalent to the "ToString" abstract operation of the specification (you get it e.g. by doing 'obj + ""' ). Calling the "toString" method of an object does not always gives the same result.
