### ISSUE TITLE
`magic` needs a tighter type specification

### ISSUE THREAD

**Issue by swimmadude66** [bellard/quickjs#152]
the `magic` value is typed as an `int` everywhere, rather than something more specific. This causes the downstream library quickjs-emscripten to have [a bug where reading the value returns a wrapped negative 16-bit integer ](https://github.com/justjake/quickjs-emscripten/pull/94). If it wouldn't break anything else, we were able to fully address this issue by simply re-typing `magic` to `uint32_t` everywhere.

Does this raise any eyebrows? My exposure to this library is only through quickjs-emscripten, so I don't know of the implications of this change on other usecases.

**Comment by bellard** [comment]
I don't see any problem with that.
