### ISSUE TITLE
StackOverflow on `number.toString(16)`

### ISSUE THREAD

**Issue by nick-thompson** [bellard/quickjs#155]
Hey, I'm hitting a StackOverflow when trying to evaluate `x.toString(16)` for `x` as various large-ish numbers (e.g. 1593571002). The error spawns from the `js_check_stack_overflow` check inside of `JS_CallInternal`. It looks like I might be able to disable the stack checking with `CONFIG_STACK_CHECK` but I don't quite see how to do that. Can you offer any pointers for navigating this issue?

**Comment by bellard** [comment]
can you provide a small piece of code to reproduce the issue ?
