### ISSUE TITLE
Regex bug

### ISSUE THREAD

**Issue by Georgezxh** [bellard/quickjs#158]
### Description
The code below does not have the same output as other engines (e.g., V8 in Google Chrome,SpiderMonkey in Firefox,graaljs,hermes,V8 in nodejs,JaegerMonkey in Firefox,JerryScript,mulversion in Firefox,chakra in Edge,carakan in Opera,nitro in Safari).

### Running code
var regex=/(?:|[\w])+([0-9])/;regex.exec("123and123")

### Output
In quickjs the output is["1","1"], however in other js engines the outputs are ["123and123","3"]

**Comment by bellard** [comment]
fixed
