### ISSUE TITLE
InternalError: unconsistent stack size when parsing generator function

### ISSUE THREAD

**Issue by rFlex** [bellard/quickjs#166]
Hey folks,

This code fails to compile with QuickJS:
```js
const anon = function*() {
    try {
        this.result = yield sync();
    } finally {
        console.log('Done');
    }
};
```
It will show `InternalError: unconsistent stack size: 3 2 (pc=46)`. This code is a vastly simplified shim from some TypeScript output that ended up not compiling with QuickJS. This issue can be reproduced by just attempting to compile this shim through `qjs`. I've tried using the address sanitizer to see if anything stood up but it didn't report anything.

**Comment by BambooLqq** [comment]
Hi, I have the same problem. Have you solved it?
