### ISSUE TITLE
Global Transpile/Parser/Code Transform hook

### ISSUE THREAD

**Issue by stevefan1999-personal** [bellard/quickjs#175]
My project, [Den](https://github.com/stevefan1999-personal/den), uses [swc-project/swc: Rust-based platform for the Web](https://github.com/swc-project/swc) as the script frontend to transpile from ESNext/TypeScript to ES2020 which QuickJS targets (well, although just for the most part). I noticed that I have to make a lot of transpilers in different location, so I would like to see if we can have a Promise API that awaits for a code transform before parsing the code on QuickJS side. 

Well, until SWC can directly output QuickJS bytecodes let's do it on a simply way. We just need to wait for a pre-parsing promise to get a new result. If there is no need to transform then it should be resolved right away and ready to be loaded in the next tick.

The API can either simply be a function of the following kind:

```
eval_hook: (src: string) => Promise<string>
```

Or if you want the file location:

```
file_transform_hook: (file: string) => Promise<string>
```

I also need it because while I can wrap around the functions that can possibly get transpiled doesn't mean the QuickJS engine itself realizes it can this can be problematic in the context such as `eval`.

**Comment by bellard** [comment]
Sorry I don't understand your needs. Please provide a simple example.

**Comment by stevefan1999-personal** [comment]
> Sorry I don't understand your needs. Please provide a simple example.

Hmm, I do realize it is not that simple to explain. I can put the swc in front of the interpreter, but it does not account for, say the following case:
```ts
function foo(): number{
  return eval("return 42 as number");
}
```
There's simply no way to let SWC to process the eval block for now, despite we already have the capability to do so.

For now, I tried to put the SWC transpiler in all possible places, including JS module import callbacks. But I doubt this is enough so I wanted to have a place to ensure the transpiler can be applied once and for all.
