### ISSUE TITLE
Inconsistent behavior in localeCompare

### ISSUE THREAD

**Issue by Georgezxh** [bellard/quickjs#179]
### quickjs version
20210327
### Description
'a' is before 'A', so the first result should be negative number. 
When adding parameter```{ sensitivity: 'base' }```, 'a' should be equal 'A', so the second result should be 0.

### Test case
```
var a = 'a'; 
var b = 'A'; 
print(a.localeCompare(b));
print(a.localeCompare(b, 'en', { sensitivity: 'base' }));
```
### Output
32
32
### Expected behavior
-1(Or other negative number)
0

**Comment by dchest** [comment]
QuickJS doesn't have `Intl.Collator`, so these parameters are ignored as [per spec](https://tc39.es/ecma262/#sec-string.prototype.localecompare):

> **22.1.3.11 String.prototype.localeCompare ( that [ , reserved1 [ , reserved2 ] ] )**
> An ECMAScript implementation that includes the ECMA-402 Internationalization API must implement this method as specified in the ECMA-402 specification. If an ECMAScript implementation does not include the ECMA-402 API the following specification of this method is used: ...

 You'll need to implement your own [internationalization API](https://www.ecma-international.org/publications-and-standards/standards/ecma-402/) or use a polyfill.

**Comment by Georgezxh** [comment]
> QuickJS doesn't have `Intl.Collator`, so these parameters are ignored as [per spec](https://tc39.es/ecma262/#sec-string.prototype.localecompare):
> 
> > **22.1.3.11 String.prototype.localeCompare ( that [ , reserved1 [ , reserved2 ] ] )**
> > An ECMAScript implementation that includes the ECMA-402 Internationalization API must implement this method as specified in the ECMA-402 specification. If an ECMAScript implementation does not include the ECMA-402 API the following specification of this method is used: ...
> 
> You'll need to implement your own [internationalization API](https://www.ecma-international.org/publications-and-standards/standards/ecma-402/) or use a polyfill.

Thanks. How about a.localeCompare(b)? Is it normal to return 32 other than a negative number?

**Comment by bellard** [comment]
Yes returning 32 (instead of 1) is valid according to the ECMA spec.
