### ISSUE TITLE
Possible Memory leak when invoke recursion case

### ISSUE THREAD

**Issue by HarlonWang** [bellard/quickjs#187]
```javascript
function memoryLeakTest(arr) {
    var stack = [];
    var count = 1;

    function recursionTest(arr) {
        stack.push(arr);
        if(count < 2) {
            count++;
            recursionTest(arr);
        }
    }
    recursionTest(arr);
}


var arrayTest = ['leak-test'];

for(let i = 0; i < 100; i++) {
	memoryLeakTest(arrayTest);
}
```

when I test above code, array objects wasn't free, it was increase count along with loop. I thought the key code was `stack.push(arr)`, it leads memory leak. If someone know this case, welcome to tell me. and I will deep analysis source code.

![image](https://github.com/bellard/quickjs/assets/2297803/62cc2b3e-ecba-408a-bbc7-8fb89a839f38)

**Comment by HarlonWang** [comment]
Add a info, when I set count to more, the array objects was reduce.
1. here was loop count with 430
![image](https://github.com/bellard/quickjs/assets/2297803/445fb86f-1f25-4f70-9ef9-711bf3faede9)


2. here was loop count with 420
![image](https://github.com/bellard/quickjs/assets/2297803/e1b920b4-33f5-4b6c-b487-78a972a9b3ba)

it seems like to trigger gc when set more loop count. I guess probably related with circular reference.

**Comment by kyaru92** [comment]
it seems that these data are for objects that are still alive in the runtime.
so gc should be taken into consideration

**Comment by bellard** [comment]
Circular references are not immediately freed. So QuickJS has heuristics to free them once the allocated memory is large enough. You can manually run the garbage collector with "std.gc()" and verify that your objects are freed.
