### ISSUE TITLE
QuickJS Project Health Check-in

### ISSUE THREAD

**Issue by benduran** [bellard/quickjs#188]
Hi there!

I've been keeping an eye on this project for a few months now, and have recently started exploring its use. I've noticed that there haven't been any commits in over a year, and there are a few Pull Requests that are still lingering in the open state.

How is everything going? Are there any plans to continue the project? Do you need any help and / or are you hoping to transition ownership at some point in the future?

There has been some excitement at Shopify regarding their [javy](https://github.com/bytecodealliance/javy) WebAssembly framework and its usage of QuickJS that may likely put more eyeballs on QuickJS.

Hope to hear from you, and thanks for building a killer project!

**Comment by Alhadis** [comment]
I've been trying to get an update on this project's status for nearly 2 years now. Neither the QuickJS mailing list nor @bellard himself have been responsive. You could try [e-mailing him](mailto:fabrice@bellard.org) directly, provided he's still alive.

**Comment by FGasper** [comment]
> I've noticed that there haven't been any commits in over a year, and there are a few Pull Requests that are still lingering in the open state.

You may note that the GitHub page specifically says to submit patches via this mailing list, not GitHub. So there would more contributions if they were received.
> How is everything going? Are there any plans to continue the project? Do you need any help and / or are you hoping to transition ownership at some point in the future?
> 
In my opinion the project needs ownership to be transferred, or a fork. Fabrice hasn’t been around for some time, and even concerns about security and correctness have gone unanswered. At my last job I advocated for QuickJS usage over a coworker’s concerns about the project’s maintenance. I’m left eating my hat (metaphorically) on that one.

If Shopify or someone else with the resources are willing to pick it up, I suspect a lot of interest would follow.

Cheers,
-Felipe

**Comment by benduran** [comment]
There is this fork, which has been a bit more lively and is in active maintenance by the OpenWebF team. This fork has also seen some performance improvements, though, I haven't yet tried them out.

https://github.com/openwebf/quickjs

**Comment by Alhadis** [comment]
> In my opinion the project needs ownership to be transferred, or a fork.

It's more complicated than that: Fabrice uses SVN,[^1] and development happens behind closed-doors. I was actually the one who nagged him into making this GitHub mirror.[^2] So any future changes made upstream will not only appear in a tagged release, but will also need to be "ported" from SVN to any forks of his Git mirror.

> I’m left eating my hat (metaphorically) on that one.

Honestly, I don't blame you for advocating. This project has _so_ much potential, and with such widespread community interest, it's insanely frustrating that Fabrice is apparently unwilling to transfer maintenance of the project (which is something he did with FFmpeg, and we all know how _that_ project turned out… 😉)

[^1]: https://www.freelists.org/post/quickjs-devel/Please-consider-moving-the-project-to-GitHub,7
[^2]: https://www.freelists.org/post/quickjs-devel/Please-consider-moving-the-project-to-GitHub

**Comment by saghul** [comment]
Hey there!

I share the sentimet here, as an early QuickJS user on my txiki.js runtime.

I had the chance to have a face to face chat with @chqrlie at FOSDEM earlier in the year and he was open to the idea.

Unfortunately things got complicated for me so I couldn't follow-up much :-/ Things are better now and I'd be happy to participate in a community effort and reignite it.

> it's insanely frustrating that Fabrice is apparently unwilling to transfer maintenance of the project

Is it necessary though? The community could gather elsewhere. I got https://github.com/quickjs-contrib but @chqrlie was working on getting https://github.com/quickjs as the new project home.

**Comment by Alhadis** [comment]
> Is it necessary though? The community could gather elsewhere.

Without an official passing of the torch (or even just definitive confirmation that QuickJS has been discontinued), there's no guarantee that Fabrice _won't_ resume development on the project after years of ostensible abandon. This can have ugly consequences for a community-led continuation of QuickJS, assuming it's managed to establish itself as a _de facto_ successor. Worst case scenario, QuickJS v2027-02-28 (or whatever) is released out-of-the-blue, turning the past 4 years of community efforts from an unofficial continuation into a feature-incompatible fork of the same name. Best case scenario, this never happens, and QuickJS lives on in multiple, divergent paths of development (à la, BSD).

These corollaries aren't supposed to be deal-breakers, but if there's a cleaner, saner way to avoid future frustration and chaos by having Fabrice agree to pass on stewardship of QuickJS to an actively-interested community… well, it'll surely contribute to a healthier future for QuickJS.

**Comment by paulocoghi** [comment]
I confess I'm more concerned with Fabrice's well-being instead of QuickJS. The last time he did something was on March 6, 2022 [(link)](https://github.com/bellard?tab=overview&from=2022-12-01&to=2022-12-31)

**Comment by saghul** [comment]
> I confess I'm more concerned with Fabrice's well-being instead of QuickJS. The last time he did something was on March 6, 2022 [(link)](https://github.com/bellard?tab=overview&from=2022-12-01&to=2022-12-31) with just one day of activity in the whole year of 2022. Also, 2021 was no different.

He is not active on GH generally speaking.

**Comment by Alhadis** [comment]
> I confess I'm more concerned with Fabrice's well-being instead of QuickJS.

I assume he's okay, judging by his recent activity in an [unrelated project](https://bellard.org/ts_server/).

> He is not active on GH generally speaking.

IIRC, the best way to get in touch with @bellard is by <a href="mailto:fabrice@bellard.org">e-mail</a>.

**Comment by saghul** [comment]
I tried to reach out as well to no avail... so here we go, QuickJS-ng :-) https://github.com/quickjs-ng/quickjs A friendly fork aiming to bring it forward in terms of features and platform compatibility.

**Comment by benduran** [comment]
Congrats @saghul ! Just saw the announcement in the ECMAScript Newsletter, too, so hopefully that makes the project gain some momentum from a consumption perspective.

I look forward to giving it a go, myself!

**Comment by saghul** [comment]
Oh what newsletter is that?

**Comment by paulocoghi** [comment]
This one: https://ecmascript.news/

In particular, the one from yesterday: https://ecmascript.news/archive/es-next-news-2023-11-28.html

**Comment by saghul** [comment]
Oh, thanks!

**Comment by cykoder** [comment]
bellard has started contributing to the repo again, so atleast for now quickjs isnt dead! happy to see work being done in GH than just the mailing list
