### ISSUE TITLE
Stack underflow with generators

### ISSUE THREAD

**Issue by Maltysen** [bellard/quickjs#189]
I'm using quickjs to run some javascript that has been run through the closure compiler and I got the error `InternalError: stack underflow (op=132, pc=1454)`. This seems to be the op code for `OP_iterator_close_return`. I noticed some unsure comments in the quickjs source where this was emitted, but I don't understand the code well enough to debug this.

Changing closure to output es2017 so it could use native async/await and avoid generators lets the code run fine, so its something related to closure's shim for async/await.

I wanted to try isolating the error, but the project is large and i don't know how to interpret the program counter the `pc=` refers to. If someone could help me with that, I'll try isolating the error.

(Running with asan/ubsan gave some null pointer and other errors, but they seem unrelated, and prolly exist in normal operation).

P.S: quickjs is awesome and u guys r awesome for building it :)

**Comment by bellard** [comment]
The last commits should fix your issue
