### ISSUE TITLE
Recommendation to transpile and bundle typescript for running in quickjs

### ISSUE THREAD

**Issue by RichardGaleSonos** [bellard/quickjs#191]
I have a typescript node app with dependencies. I can build with webpack and run via node or execute directly with ts-node, now I would like to run via quickjs. Are there any examples of transpiling to the appropriate versioned javascript, including dependencies, and creating a bundle?

I'm happy to use esbuild, rollup, weback, etc.

**Comment by paulocoghi** [comment]
You can easily bundle all your code to a single JS file using Rollup or any other standard bundler. Even bun.sh is a valid (and really fast) option for this task.

But the real issue here is compatibility, since QuickJS is not equivalent nor compatible to NodeJS, due to the large differences on their standard libraries*.

If all the javascript code, including the dependencies, do not use any specific feature from Node stdlib (very unlikely), then its fully compatible with QuickJS.

* To the surprise of many, yes, QuickJS does provide a standard library ([link](https://bellard.org/quickjs/quickjs.html#Standard-library))

**Comment by RichardGaleSonos** [comment]
> But the real issue here is compatibility, since QuickJS is not equivalent nor compatible to NodeJS, due to the large differences on their standard libraries [1].

Agree on the libraries. Firstly I need QuickJS to accept and parse my JS. Which means transpiling from typescript to some ECMA version including the dependencies in node_modules.

**Comment by paulocoghi** [comment]
Depending on how much control you have over your javascript code (including dependencies), and on how much you really want to run in on QuickJS, you can translate the code related to standard librarie usage, and use QuickJS's one, eventually using additional helping libraries (like an [HTTP server library](https://github.com/QuickJS-Web-project/quickwebserver) for quickjs), but you really need to know your goal and evaluate if QuickJS is a good choice for your scenario.

**Comment by paulocoghi** [comment]
Here is an example (not tested) of a `rollup.config.js` to transpile and "three-shake" your code to a single optimized final bundle ins ECMA

```js
import dts from 'rollup-plugin-dts'
import esbuild from 'rollup-plugin-esbuild'

export default [
{
	input: `src/your-main-file.js`,
	plugins: [esbuild()],
	output: [
	{
		file: `dist/bundle.js`,
		format: 'cjs',
		sourcemap: true,
		exports: 'default',
	},
	]
}]
```

**Comment by RichardGaleSonos** [comment]
100% control of my javascript. 100% my choice of dependencies. 100% committed to running embedded QuickJS.

**Comment by paulocoghi** [comment]
When possible, give a feedback about the example approach above (with Rollup)

**Comment by guest271314** [comment]
What issues are you having running the JavaScript that TypeScropt compiles to JavaScript in QuickJS environment?

**Comment by RichardGaleSonos** [comment]
I had some require("") statements in packages under node_modules that hadn't been converted.

**Comment by paulocoghi** [comment]
@RichardGaleSonos Were you able to create a single bundled javascript with the example I gave you above?

**Comment by RichardGaleSonos** [comment]
esbuild() does not appear to be handling my TS files. Using your rollup.config.js I get "RollupError: The keyword 'enum' is reserved"

**Comment by paulocoghi** [comment]
@RichardGaleSonos, when possible, please install Bun ([bun.sh](https://bun.sh/)) and use its bundler (bun build), as the following example:

- **By creating a bundler.js and running `bun bundler.js`**
```js
// bundler.js
await Bun.build({
  entrypoints: ['./src/index.ts'],
  outdir: './dist',
});
```

- **Or, directly through cli:**
```
bun build ./src/index.ts --outdir ./dist
```

**Comment by guest271314** [comment]
Another option is the deprecated `deno bundle test.ts test.js` or `deno_emit`

```
import { bundle } from "https://deno.land/x/emit/mod.ts";
const result = await bundle(
  'test.ts',
);

const { code } = result;
console.log(code);
```

**Comment by RichardGaleSonos** [comment]
Thank you.

bun worked for me, generating a single .js file that quickjs could parse, I'm running it as a dependency of txiki.js

Now I need to resolve, "ReferenceError: could not load 'node:fs'" this was expected.

**Comment by paulocoghi** [comment]
IMHO, unless there is some particular feature provided by txiki.js, I would recommend pure QuickJS over it, considering txiki.js also uses libuv (used by NodeJS) which, in the end, negates many (if not most of) possible benefits of going to an alternative and _smaller_ runtime.

**Comment by RichardGaleSonos** [comment]
I need node:fs, node:dgram, etc. My goal is to run a node app in a smaller footprint that running node itself.

**Comment by paulocoghi** [comment]
For `node:fs`, quickjs [stdlib](https://bellard.org/quickjs/quickjs.html#Standard-library) would be enough (through FILE prototype).

But `node:dgram` (UDP datagram sockets) is another thing. If txiki.js provides it, go for it :)
