### ISSUE TITLE
`Date` constructor is not at parity with JS

### ISSUE THREAD

**Issue by swimmadude66** [bellard/quickjs#193]
Some values which work for `new Date` in js create invalid dates in quickJS

The `Date` constructor referenced in the MDN page for `Date` works in JS, but creates an invalid date in Quickjs

```
// js (like chrome console)
const d = new Date('December 17, 1995 03:24:00') //-> valid Date
isNaN(d) // false

// quickjs
const d = new Date('December 17, 1995 03:24:00') // -> Date, but invalid
isNaN(d) // true
```

it seems to be something with the argument parsing of the constructor, since `new Date(819195840000` (the numeric value of the date above) works in both environments

**Comment by andy0130tw** [comment]
The ECMAScript specification says that the format `Date` constructor can parse is [implementation-defined](https://262.ecma-international.org/#sec-date.parse), except for the [date time string format](https://262.ecma-international.org/#sec-date-time-string-format) (YYYY-MM-DDTHH:mm:ss.sssZ) which it must support.
