### ISSUE TITLE
How to use shebang?

### ISSUE THREAD

**Issue by mwisnicki** [bellard/quickjs#197]
```
#!/bin/qjs
console.log("Hello");
```

It doesn't work when invoked from bash as script:

```
$ ./test.qjs
./test.qjs: line 2: syntax error near unexpected token `"Hello"'
./test.qjs: line 2: `console.log("Hello");'
$ qjs test.qjs
Hello
```

**Comment by ctn-malone** [comment]
Try `#!/usr/bin/env -S /bin/qjs --unhandled-rejection -m`

**Comment by mwisnicki** [comment]
@ctn-malone thanks, actually this didn't work but I realized it's a problem with [Cosmopolitan](https://justine.lol/cosmo3/) build of qjs.

Native qjs works just fine with `#!/bin/qjs` and `#!/usr/bin/env qjs`
