### ISSUE TITLE
Support navigator.userAgent

### ISSUE THREAD

**Issue by guest271314** [bellard/quickjs#205]
See https://github.com/wintercg/proposal-common-minimum-api/issues/62#issuecomment-1849021888.

**Comment by bellard** [comment]
"navigator.userAgent" is a browser API and has no relation with QuickJS. You can use for example globalThis.hasOwnProperty("std") to test if the QuickJS C library is present.

**Comment by guest271314** [comment]
They're working on that Minimum Common API of Web API's proposal targeting non-browser runtimes. txiki.js is on board https://github.com/saghul/txiki.js/issues/418. If you're not, cool. Thanks for bringing forth QuickJS. Have a great day.
