### ISSUE TITLE
JSON.parse broken

### ISSUE THREAD

**Issue by lastmjs** [bellard/quickjs#206]
In Chrome, Node, and Firefox this works just fine:

```javascript
JSON.parse('19686109595169230000')
// 19686109595169230000
```

In QuickJS in wasm32-wasi (using Javy) and on my Ubuntu laptop x86 this is broken:

```javascript
JSON.parse('19686109595169230000')
// 19686109595169227000
```

**Comment by ulan** [comment]
`JSON.parse()` uses `parseFloat()` under the hood, so all integers in JSON are treated as floating point numbers and precision errors are expected.

That said, the spec requires that `parseFloat()` is consistent with parsing of literals in the program:
```
> let x = 19686109595169230000;
> let y = parseFloat("19686109595169230000");
> x == y
```
This should return `true`, but currently it returns `false` and it appears to be a bug indeed.

I debugged the issue to this part of `js_strtod`: https://github.com/bellard/quickjs/blob/4bb8c35da7c83b5eb67541772b857e822da855da/quickjs.c#L9976
Precision errors are introduced when a large `n` is assigned to double `d`.

One way to fix this issue would be to restrict the fast-path parsing only to integers up to 2^53 and fall back to the slower `strtod` for larger integers:
https://github.com/ulan/javy/commit/149ff4cccfc4ba259a568f7eb3aa200e2a5c8bf5

**Comment by bellard** [comment]
fixed
