### ISSUE TITLE
Can quickjs work with cosmopolitan 3+ ?

### ISSUE THREAD

**Issue by serapath** [bellard/quickjs#207]
I am JS and not a C programmer, but the idea of having a quickjs based JS runtime that can run on bare metal sounds interesting to me. This is what the APE format and cosmopolitan promise to do.
https://github.com/jart/cosmopolitan

So far I was not able to make it work, but being new to all this, I thought I might just open an issue and ask if that is even possible at all.

**Comment by leeoniya** [comment]
you're likely to get a faster answer in that repo

**Comment by bellard** [comment]
Good idea. Cosmopolitan will be natively supported in the next release.
