### ISSUE TITLE
Vue.js use WeakMap  Memory Leak

### ISSUE THREAD

**Issue by wy676579037** [bellard/quickjs#211]
function createReactiveObject(
  target: Target,
  isReadonly: boolean,
  baseHandlers: ProxyHandler<any>,
  collectionHandlers: ProxyHandler<any>,
  proxyMap: WeakMap<Target, any>
) {
  if (!isObject(target)) {
    if (__DEV__) {
      console.warn(`value cannot be made reactive: ${String(target)}`)
    }
    return target
  }
  // target is already a Proxy, return it.
  // exception: calling readonly() on a reactive object
  if (
    target[ReactiveFlags.RAW] &&
    !(isReadonly && target[ReactiveFlags.IS_REACTIVE])
  ) {
    return target
  }
  // target already has corresponding Proxy
  const existingProxy = proxyMap.get(target)
  if (existingProxy) {
    return existingProxy
  }
  // only specific value types can be observed.
  const targetType = getTargetType(target)
  if (targetType === TargetType.INVALID) {
    return target
  }
  const proxy = new Proxy(
    target,
    targetType === TargetType.COLLECTION ? collectionHandlers : baseHandlers
  )
  proxyMap.set(target, proxy)
  return proxy
}

export const reactiveMap = new WeakMap<Target, any>()

在这里Proxy can not release

**Comment by wy676579037** [comment]
https://github.com/vuejs/core/blob/a8d0b1b38b092ec2d10b32bedcee2eea33b77657/packages/reactivity/src/reactive.ts#L248

**Comment by bellard** [comment]
Sorry but without a standalone example it is not possible to fix the issue
