### ISSUE TITLE
How can I get the length of an array and iterate in C?

### ISSUE THREAD

**Issue by mengbai123** [bellard/quickjs#213]
I looked quick.c code, which has a similar operation, but it is too complicated, and many use a lot of private functions, which are not open to the public, such as js_get_length32.

**Comment by nickva** [comment]
Wonder if something like this would work, with proper error checking and deallocating as needed after each call:

```c
JSValue val;
uint32_t len, i;

val = JS_GetPropertyStr(ctx, arr, "length");
JS_ToUint32(ctx, &len, val);
for(i = 0; i < len; i++){
   val = JS_GetPropertyUint32(ctx, arr, i)
}
```

**Comment by mengbai123** [comment]
Thanks, it really helped me.
