### ISSUE TITLE
Feature request: regex engine replacement

### ISSUE THREAD

**Issue by stevefan1999-personal** [bellard/quickjs#215]
I would like to port the regex engine from the internally developed LRE to PCRE2, that way we can have JIT support for the regex if possible, however, it seems like the QJS internal for RegExp is highly coupled with LRE.

Hacking the RegExp prototype should be easy enough to replace LRE:
https://github.com/bellard/quickjs/blob/9a4379daf69b68b3196613be11c0ef4e19203ef3/quickjs.c#L44744-L44802

I can implement an interface to PCRE2 by mimicking the prototype, however this means the user needs to take the initiate to use my RegExp object and may not work for internal functions with surprising cases.

For example, the RegExp "operator" stores the serialized LRE bytecodes as byte strings directly into the QJS bytecode stream, and thus I cannot merely replace the Regex engine if I have precompiled QJS bytecode, and it will obviously crash:

https://github.com/bellard/quickjs/blob/9a4379daf69b68b3196613be11c0ef4e19203ef3/quickjs.c#L24367-L24402

https://github.com/bellard/quickjs/blob/9a4379daf69b68b3196613be11c0ef4e19203ef3/quickjs.c#L16708-L16714

For this operator problem though, a not-so workaround is to simply ignore the stored bytecode, so that we can recompile the regex every time. If I read the operator correctly, I can just make a function that returns an empty string for `s->ctx->compile_regexp`, and so the engine should always use the pattern instead. 

It is also possible for PCRE2 to serialize the regex as its own internal bytecode format too, but this would not play well with the OG QJS engine which uses LRE by default.

**Comment by bellard** [comment]
It is unlikely that PCRE2 has the same semantics as the JS RegExp. Moreover, I see no advantage in using PCRE2 as it  introduces a very large dependency (almost as large as the whole QuickJS binary !) so there is no chance that such a patch would be merged. Anyway, in order to do it, you should modify the QuickJS code in order to store the compiled bytecode in the JSRegExp structure.
