### ISSUE TITLE
Separate the built-in intrinsic feature implementations into different C files and then amalgamate them back together

### ISSUE THREAD

**Issue by stevefan1999-personal** [bellard/quickjs#216]
The source code for quickjs.c is currently at 55K lines, and it is expected the grow. We should consider splitting the intrinsic implementations into its own C files, and then we can `#include` them back again.

For example, we can split the atomic intrinsic support into `intrinsic/atomics.c` and then `#include "intrinsic/atomics.c"` back again in the quickjs.c file. 

This way, hacking the actual QJS engine source code itself would be cleaner and easier. We can do more by formally splitting the intrinsic code into its own translation unit (that means into its own object file), but I think that is not going to be easy at the moment.

**Comment by bellard** [comment]
It is possible that the buitins will be moved to a separate translation unit someday in order to speed up the compilation. However, I see no advantage in splitting with several #include. Having large source files is not a problem for me.
