### ISSUE TITLE
Won't compile for windows

### ISSUE THREAD

**Issue by ClosetGeek-Git** [bellard/quickjs#224]
Loving quickjs, but having an issue finding pthreads while linking with mingw32. What is the best way to proceed? I'm not familiar with mingw32

**Comment by buke** [comment]
I'm also not familiar with mingw32,  I using docker multiarch/crossbuild image to compile win32/64 static lib,
`
    - name: Build windows amd64
      if: matrix.platform == 'ubuntu-latest'
      run: mkdir -p deps/libs/windows_amd64 && cd deps/quickjs && docker run --rm -v $(pwd):/workdir -e CONFIG_WIN32=y -e CROSS_TRIPLE=x86_64-w64-mingw32 multiarch/crossbuild /bin/bash -c "cd /workdir && make clean && make libquickjs.a "  && mv libquickjs.a ../libs/windows_amd64

    - name: Build windows 386 
      if: matrix.platform == 'ubuntu-latest'
      run: mkdir -p deps/libs/windows_386 && cd deps/quickjs && docker run --rm -v $(pwd):/workdir -e CONFIG_WIN32=y -e CONFIG_M32=y -e CROSS_TRIPLE=i686-w64-mingw32 multiarch/crossbuild /bin/bash -c "cd /workdir && make clean && make libquickjs.a "  && mv libquickjs.a ../libs/windows_386

`

[https://github.com/buke/quickjs-go/blob/main/.github/workflows/build.yml#L34C1-L41C1](url)

maybe it could help you

**Comment by ClosetGeek-Git** [comment]
Tying it now

**Comment by ClosetGeek-Git** [comment]
@bellard what linux distro do you use when developing and cross-compiling quickjs? I'm wondering if this is a packaging issue with Ubuntu.

**Comment by bellard** [comment]
I am using Fedora. It must be a packaging issue.

**Comment by ClosetGeek-Git** [comment]
Thank you @bellard, and yes, it was a Ubintu package issue. Fedora has mingw64-winpthreads  mingw64-winpthreads-static available and it works without issue. I spent hours looking for similar packages for Ubunut. They may be out there and someone more experienced with mingw64 may know exactly where but they're mainline packages for Fedora.
