### ISSUE TITLE
Is there a reason for not installing quickjs-atom.h in make install?

### ISSUE THREAD

**Issue by xeioex** [bellard/quickjs#229]
How to get a value for a well-known symbol directly (not quering Symbol object), like `Symbol.isConcatSpreadable`, if quickjs-atom.h is not included?

**Comment by bellard** [comment]
quickjs-atom.h is considered as a private header, so it should not be used in user code. So it is better to query the Symbol Object. A specialized version of __JS_NewAtom() for symbols could also be exported.
