### ISSUE TITLE
Implicit await in repl for Promises?

### ISSUE THREAD

**Issue by Emill** [bellard/quickjs#231]
```
$ ./qjs
QuickJS - Type "\h" for help
qjs > new Promise((resolve, reject) => {});
```
qjs appears to stop here and does not emit `qjs >` after this.

It appears as if an expression results in a Promise, that Promise is automatically awaited. More generally, it appears qjs prepends an implicit `await` to every line.

I would expect that the Promise object is printed instead (immediately), just like e.g. Chrome's developer console or node.js repl does. Only if the `await` keyword is used, the Promise should be awaited.

**Comment by bellard** [comment]
fixed
