### ISSUE TITLE
shebang support for qjs

### ISSUE THREAD

**Issue by maroziza** [bellard/quickjs#243]
I'm going to use qjs as system script interpreter. it works perfectly good, i added ioctl call as an shared library and qjs can configure all the system now but i have a problem running scripts with eXecutable status,
So adding  `#!/bin/qjs` as the first line of the script renders file unrunnable. 
I think there should be an option to run it as script interpreter and skip the first line.

For Node.js it can (but often doesn’t) look like this:

`#!/usr/bin/node`

Node.js will happily ignore this as a comment only if it is the very first line of the file (it won’t work even if there’s an empty line or //comment line before it). Browsers [ignore it](https://github.com/tc39/proposal-hashbang) too (Chrome 74+, FF 67+).

I want also to note, that shebang is limited to 127 chars on 99.9% of systems due to kernel compile time buffer limit. It's limited in the kernel by BINPRM_BUF_SIZE.

**Comment by saghul** [comment]
There is code to support that in qjs, what error do you get?

**Comment by maroziza** [comment]
thanks, double checked the env and it was older branch of qjs, now it works
