### ISSUE TITLE
which libc ?

### ISSUE THREAD

**Issue by fperrad** [bellard/quickjs#33]
Now, **quickjs** is packaged in [buildroot](https://buildroot.org/),
see details on <https://git.busybox.net/buildroot/tree/package/quickjs?h=next>.
The cross compilation support (with `CROSS_PREFIX`) works well.

Buildroot allows to build against various libc :
- glibc
- musl which doesn't support `stdatomic`
- uClibc-ng which doesn't support `fenv`

At this time, it seems that **quickjs** requires a `glibc`.

Have you plan to support others libc 
or just to  add the `glibc` dependency in the documentation ?

**Comment by bellard** [comment]
stdatomic is optional for QuickJS (disable CONFIG_ATOMICS in quickjs.c). The shared arrays won't be present though.

QuickJS relies on printf to do exact rounding when printing floating point numbers. fenv is only used here so the dependency could be removed if it is accepted that some numbers won't be printed in a spec compliant way. It is expected that this dependency on the libc will be removed at some point.

**Comment by fperrad** [comment]
Update: on Buildroot, the build with `musl` works too.
