### ISSUE TITLE
docs: website typo

### ISSUE THREAD

**Issue by agorushkin** [bellard/quickjs#330]
Wasn't sure where to leave this at since I couldn't find the repository of the https://quick.js.org/docs.

Under the `setCSS()` over at https://quick.js.org/docs#setcss, it says `Removes a class from an element`, which I'm assuming was forgot to be edited after copying the markdown of the `removeClass()` function above with the same description.

Apologies in advance if this is not the right space for pointing this issue out.

**Comment by saghul** [comment]
This project is not the same you linked, though they have the same name 😅

**Comment by agorushkin** [comment]
Oh my god, I'm so sorry. I've had two tabs open, one for this project and one for the project on the website, and given the name similarity accidentally created an issue here. https://github.com/proudparrot2/quick.js this is the project I meant to create an issue on.

Apologies again, I'll close this issue to avoid any more confusion.
