### ISSUE TITLE
Access module exports from native code

### ISSUE THREAD

**Issue by letmaik** [bellard/quickjs#34]
In [CCF](https://github.com/microsoft/CCF) we've been using a patch from user Geequlim to access modules exports, specifically functions, from native code:

https://www.freelists.org/post/quickjs-devel/Patch-Add-some-informations-to-get-more-informations-from-compiled-modules

Is there a chance to make this part of quickjs? I'm not sure if the patch requires further tweaks to work more generally. I think it doesn't work as-is when a function/entry is re-exported from another module.

We're happy to help if it's useful.

**Comment by kasperisager** [comment]
For reference, we've added something similar to our fork: https://github.com/holepunchto/quickjs/commit/6003747a89d63b387c720869c16cd20951de53d2

**Comment by bellard** [comment]
done
