### ISSUE TITLE
Static linked binary generation

### ISSUE THREAD

**Issue by nv08** [bellard/quickjs#343]
Does anyone have created a `static linked `binary using `qjsc` ?
Please guide me to the command if possible.
Currently using  `qjsc -o out main.js`
generating file of type :- 
`out: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=284156e75cf2df70bff9cfbf085f251c76beb7d3, for GNU/Linux 3.2.0, with debug_info, not stripped`

**Comment by ctn-malone** [comment]
If your main target is linux, you can check https://github.com/ctn-malone/quickjs-cross-compiler which does just that
