### ISSUE TITLE
Question: how many CPU cores does V8 use in benchmark?

### ISSUE THREAD

**Issue by linrongbin16** [bellard/quickjs#347]
Hi,

In the benchmark https://bellard.org/quickjs/bench.html, I am not sure how many CPU cores does V8 and QuickJs use?

Because in my knowledge, V8 can use multiple threads to improve the performance, especially the garbage collection.

**Comment by chqrlie** [comment]
QuickJS uses a single core at all times.

**Comment by linrongbin16** [comment]
> QuickJS uses a single core at all times.

Yes, while V8 seems can use one or more threads (in my knowledge, please correct me if I'm wrong). I feel like the benchmark is not fair if they use different threads.
