### ISSUE TITLE
Very slow to compile even when changing a single file

### ISSUE THREAD

**Issue by rubenlg** [bellard/quickjs#369]
At least for those of us without cutting-edge CPUs, contributing to quickjs is really painful, because each small change takes a very long time to compile.

When LTO is enabled, a change to `quickjs.c` requires 1m 21s to generate `qjs` in my CPU, most of the time when linking, as compiling `quickjs.c` takes only 10 seconds. When LTO is disabled it still takes about 45 seconds to generate `qjs`, but in this case almost all of the time is spent compiling `quickjs.c`. That's slow enough to get distracted with something else during compilation.

One possible solution would be to split `quickjs.c` into several compilation units and keep LTO disabled during development. That way, changes contained in a single small-ish compilation unit would have a much faster turnaround.

What do you think?

**Comment by chqrlie** [comment]
Breaking **quickjs.c** into smaller files is not being considered for multiple reasons, not the least of which is we aim to converge with the friendly fork and this would make it much more difficult.

I am curious what system you are using to experience such slow compile times.  Disabling LTO seems the right path on your system to cut build time.  But 45 seconds total when compiling **quickjs.c** itself only takes 10 seconds indicates time must be wasted is a way that breaking this file into small pieces would not solve.

You might also disable optimisations to reduce build time when you are just experimenting small changes incrementally.

**Comment by rubenlg** [comment]
My CPU is an Intel i7-4770 CPU @ 3.40GHz. I have 16GB of DDR2 RAM and the hard drive is an SSD. The OS is Ubuntu 24.04.1.

Sorry, I wasn't aware of that fork you mention. I just started using quickjs as a replacement for V8 in my project a week ago, and I'm planning to contribute a profiling patch, inspired by #184.

To clarify, compiling `quickjs.c` only takes 10s when using LTO (I suppose the compiler works much less because it lets the linker do the heavy work). When I disable LTO, all 45 seconds are spent compiling `quickjs.c`, and the linking state completes almost immediately.

I'll try with disabling optimizations during development. Thanks!

I'll close the issue. What's the best way for me to keep track on the merge of that fork you mentioned? I'd like to keep an eye to potentially reopen this once it's done.
