### ISSUE TITLE
 Are there plans to support JIT in the future?

### ISSUE THREAD

**Issue by qujianbiao** [bellard/quickjs#37]

**Comment by ScSofts** [comment]
It seems "NO".

**Comment by bellard** [comment]
No plan as it would be in contradiction with the project goals (small code, reasonably simple and portable).

**Comment by kungfooman** [comment]
You can transpile TypeScript to Lua and run via LuaJIT: https://typescripttolua.github.io/

LuaJIT is quite portable, list of JIT targets: https://github.com/LuaJIT/LuaJIT/tree/v2.1/src/jit
