### ISSUE TITLE
class_id biger than max of uint16_t may cause serious problem

### ISSUE THREAD

**Issue by chexiongsheng** [bellard/quickjs#38]
typedef uint32_t JSClassID;
but store as uint16_t in the JSObject.
Invoke JS_NewClass use a class_id biger than maximum of uint16_t will success.
Invoke JS_NewObjectProtoClass use that class_id sueccss too, but the object created store a wrong class_id. 
It may cause a wrong finalizer calling in the gc.

**Comment by bellard** [comment]
fixed
