### ISSUE TITLE
Where is the project’s main development repository?

### ISSUE THREAD

**Issue by jirutka** [bellard/quickjs#39]
According to https://bellard.org/quickjs/, this repository is just a mirror and there’s no proper commits history, just releases. Thus I’d like to ask, where can we find the project’s main (upstream) repository used for development?

**Comment by Alhadis** [comment]
The author [has stated](https://www.freelists.org/post/quickjs-devel/Please-consider-moving-the-project-to-GitHub,7) that development isn't public, and he prefers to use SVN instead of Git for version control:

> **On 9/7/20 10:40, Fabrice Bellard wrote:**
> No pull requests. I have my own repository using subversion and I don't wish to publish it now.
>
> Best regards,
>
> Fabrice.

**Comment by jirutka** [comment]
Thanks for the response. This is really sad, better to avoid such project.

**Comment by Alhadis** [comment]
@jirutka How is it sad? Not everybody's workflow is the same. Some devs prefer to accept contributions as an e-mailed patch ([including](https://git-send-email.io/) the Git and Linux Kernel projects themselves!). Not making development public is a personal choice: it's no different to having a huge-ass commit staged locally, but never committed (I happen to be guilty of that now… 😓)
