### ISSUE TITLE
qjsc not distributed as part of linux binaries

### ISSUE THREAD

**Issue by sanathusk** [bellard/quickjs#48]
None of the download links for binary releases of Linux at https://bellard.org/quickjs/ contain qjsc executable. The downloaded zip only contains qjs,run-test262 binaries.
Is any particular reason behind not including the qjsc binary in the zip? Currently, the only official way to get qjsc is by building them from source.

**Comment by aloysius-pgast** [comment]
I'm maintaining [static versions](https://github.com/ctn-malone/quickjs-cross-compiler) of the linux binaries (based on musl lib) for i686, x86_64 & arm, with the qjsc binary also producing static executables

**Comment by ctn-malone** [comment]
I'm maintaining [static versions](https://github.com/ctn-malone/quickjs-cross-compiler) of the linux binaries (based on musl lib) for i686, x86_64 & arm, with the qjsc binary also producing static executables

**Comment by bellard** [comment]
Distributing qjsc implies distributing libraries and headers so it is more complicated than just adding qjsc.
