### ISSUE TITLE
Not support top-level-await

### ISSUE THREAD

**Issue by jim-king-2000** [bellard/quickjs#52]
'top-level-await' is a killer feature. I suggest quickjs to support it.

**Comment by bellard** [comment]
No plan to support it yet.

**Comment by jaredkrinke** [comment]
I was also expecting top-level `await` to work for a module (e.g. `qjs -m file-with-top-level-await.js`), so consider this a +1 to supporting this.

**Comment by saghul** [comment]
There is patch adding support for it on the mailing list.

**Comment by jaredkrinke** [comment]
I *think* this commit includes the patch mentioned above:

https://github.com/saghul/txiki.js/commit/c0ade677aa8fe229bcd31406a3e568ebeab4e149

**Comment by tionis** [comment]
> No plan to support it yet.

As it has been nearly 3 years since then, are there still no plans to support this.
If not why?

**Comment by saghul** [comment]
It's already supported in master.

**Comment by tionis** [comment]
Oh, then I have overlooked it.
Thanks for the clarification!
