### ISSUE TITLE
A performance problem about Array.prototype.unshift

### ISSUE THREAD

**Issue by YaoHouyou** [bellard/quickjs#54]
#### Description 
When calling Array.prototype.unshift, the execution speed of quickjs is much slower than other JavaScript engines. What caused this problem? Does this problem need to be optimized?

#### Version
quickjs-2020-11-08

#### Testcase

```javascript
var foo = function(v) {
    for(var t = [], r = 0; r < 10000; r++) {
        t.unshift(1);
    }
}
var res = foo();
```

#### Execution time
quickjs:  1188ms
[JerryScript](https://github.com/jerryscript-project/jerryscript): 29ms
[XS](https://github.com/Moddable-OpenSource/moddable): 79ms

#### CPU

```
Intel(R) Core(TM) i9-9940X CPU @ 3.30GHz
```

**Comment by bellard** [comment]
fixed
