### ISSUE TITLE
[DateAPI] Date parse error

### ISSUE THREAD

**Issue by anuragagrawal-g** [bellard/quickjs#57]
Below are the few examples of the DateAPI where parse method is returning incorrect values. 

`console.log(Date.parse('04 Dec 1995 00:12:00 GMT'));` returns `-56797387680000` rather than `818035920000`
`console.log(Date.parse('2020-04-20T18:30:0000:0000'));' returns `1587432600000` rather than `NaN`
There are a few other cases/formats where parse method returns unexpected values. Also, similar issue happens with Date constructor.

**Comment by bellard** [comment]
Note: the first date ('04 Dec 1995 00:12:00 GMT') will return NaN as it is not supported by QuickJS.

**Comment by bellard** [comment]
fixed
