### ISSUE TITLE
support for stdin

### ISSUE THREAD

**Issue by laptrinhvui000** [bellard/quickjs#63]
I try to find buildin function for stdin like cin or scanf but I can't. Not include in std or global yet
For example, in d8 shell, google use readline() to input when typing in console 
<img width="555" alt="Screen Shot 2021-05-08 at 9 18 25 AM" src="https://user-images.githubusercontent.com/80116059/117522663-d2d97800-afde-11eb-9388-cd1a39c63757.png">

**Comment by nykula** [comment]
[std](https://bellard.org/quickjs/quickjs.html#std-module).out.puts("name?");
var name = std.in.getline();

**Comment by laptrinhvui000** [comment]
> [std](https://bellard.org/quickjs/quickjs.html#std-module).out.puts("name?");
> var name = std.in.getline();
It's halt after std.in.getline(); on mac os (brew install quickjs)
<img width="535" alt="Screen Shot 2021-05-09 at 11 47 09 AM" src="https://user-images.githubusercontent.com/80116059/117560922-5f0d9d00-b0bc-11eb-8101-8f97af9f1feb.png">

**Comment by nykula** [comment]
Try it in a script file, outside the REPL. It's a blocking function so I think it'll interfere with the REPL main loop which uses the stdin too.

**Comment by laptrinhvui000** [comment]
Thanks! the script work with: qjs script.js .
