### ISSUE TITLE
How Can I Force Garbage Collection?

### ISSUE THREAD

**Issue by evalPenny** [bellard/quickjs#71]
Is there a JavaScript function to force Garbage Collection?
Some JS environments have a function that forces garbage collection in JS. Chrome's window.gc, IE's window.CollectGarbage and Opera's window.opera.collect are few examples. Does this exist in QuickJS?

**Comment by mikezackles** [comment]
Try [`JS_RunGC`](https://github.com/bellard/quickjs/blob/master/quickjs.h#L347)
