### ISSUE TITLE
please consider adding a tag for previous "horhof" history

### ISSUE THREAD

**Issue by saurik** [bellard/quickjs#72]
So, because the @horhof "unofficial" repository had been blessed by QuickJS as a mirror for their project, I ended up relying on it to get access to get access to the code for this project as part of a git submodule cluster. In the last few days, I've noticed that that repository has disappeared, which is fine: there is this repository now... only it isn't actually related to the verifiable history of the prior "mirror", which means that the history of my project is now unable to be reproduced without going through some heroics. This would be almost fully mitigated if this repository offered the previous history by making it ref-accessible. The least impactful way to do this is to simply make a tag (maybe "horhof") of the previous repository's content. To be clear: this would have no visible impact on the repository's main/master branch, as it would be an unrelated history that has merely been tagged (so there wouldn't even be any branch at all, to avoid any possible confusion with people wondering if development effort had taken place on it). Personally, I would argue that, as the horhof repository had been listed on the website--and described as a "mirror" (like, official or unofficial, a "mirror" has implications)--that this would be a "friendly" level of backwards compatibility for those of us who used that repository :(.

**Comment by saurik** [comment]
@bellard Thank you very much for considering this and even apparently marking it as "completed", but I am not actually seeing any branches or tags on this repository (other than HEAD/master). (FWIW, no matter how many years I have been working with git, I often forget to push alternate branches. If there is need to find a copy of this old repository's content still, I have been forced to host a mirror of the old horhof "mirror" at [this github repo](https://github.com/orchidtechnologies/quickjs).)

**Comment by bellard** [comment]
Sorry I should have commented: I won't add this branch. You can easily use "diff" to see what are the differences between the repo you used and the quickjs official checkpoints.
