### ISSUE TITLE
os.close without arguments

### ISSUE THREAD

**Issue by nagayev** [bellard/quickjs#73]
I called `os.close` without passing any arguments and my terminal stucked. Is it normal?
I think it would be better if QuickJS throws an exception.

**Comment by bellard** [comment]
It is true that we could add a protection but it is not consistent with all the other native functions which silently accept invalid file handles. So I prefer not changing anything at this point.

**Comment by nagayev** [comment]
@bellard maybe the best way is set fd = -1 by default.
