### ISSUE TITLE
Error when trying to build quickjs on Raspberry Pi OS

### ISSUE THREAD

**Issue by David-Apps** [bellard/quickjs#75]
When I use the "make" command on Raspberry Pi OS, I get the following output:

gcc -g -flto -rdynamic -o qjs .obj/qjs.o .obj/repl.o .obj/quickjs.o .obj/libregexp.o .obj/libunicode.o .obj/cutils.o .obj/quickjs-libc.o .obj/libbf.o .obj/qjscalc.o -lm -ldl -lpthread 
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid abstract instance DIE ref
/tmp/cc5lAPns.ltrans3.ltrans.o: in function `js_atomics_store':
<artificial>:(.text+0x6f60): undefined reference to `__atomic_store_8'
/usr/bin/ld: /tmp/cc5lAPns.ltrans3.ltrans.o: in function `js_atomics_op':
<artificial>:(.text+0x776c): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: <artificial>:(.text+0x7788): undefined reference to `__atomic_fetch_and_8'
/usr/bin/ld: <artificial>:(.text+0x77a4): undefined reference to `__atomic_fetch_or_8'
/usr/bin/ld: <artificial>:(.text+0x77c0): undefined reference to `__atomic_fetch_sub_8'
/usr/bin/ld: <artificial>:(.text+0x77dc): undefined reference to `__atomic_fetch_xor_8'
/usr/bin/ld: <artificial>:(.text+0x77f8): undefined reference to `__atomic_exchange_8'
/usr/bin/ld: <artificial>:(.text+0x7820): undefined reference to `__atomic_compare_exchange_8'
/usr/bin/ld: <artificial>:(.text+0x7834): undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make: *** [Makefile:188: qjs] Error 1

One way to get the "make" command to succeed is to change the following line in the "Makefile" file:

LIBS=-lm

to:

LIBS=-lm -latomic

**Comment by molecular** [comment]
THANK YOU!!!
