### ISSUE TITLE
Bytecode incompatibility between Emscripten and non-Emscripten builds due to CONFIG_ATOMICS

### ISSUE THREAD

**Issue by kostyaby** [bellard/quickjs#76]
Hey there,

One thing that I came across recently is that QuickJS bytecode is incompatible between Emscripten and non-Emscripten builds due to the CONFIG_ATOMICS define. It's happening cuz 3 additional atoms are defined in `quickjs-atom.h` ([here](https://github.com/bellard/quickjs/blob/master/quickjs-atom.h#L180-L184)) when the bytecode is generated on Linux and this makes all atom IDs shifted by 3 when interpreted inside WASM module. An easy fix would be to define those 3 atoms anyways (a tiny bit wasteful, but makes bytecode fully compatible) - curious to hear if you think it's a good solution or is there a better way around

Thanks!

**Comment by bellard** [comment]
fixed
