### ISSUE TITLE
Macro definition error：JS_VALUE_IS_BOTH_INT in quickjs.h?

### ISSUE THREAD

**Issue by J5ive** [bellard/quickjs#82]
line 247 in quickjs.h:
#define JS_VALUE_IS_BOTH_INT(v1, v2) ((JS_VALUE_GET_TAG(v1) | JS_VALUE_GET_TAG(v2)) == 0)

It seems not right in JS_STRICT_NAN_BOXING mode, because JS_TAG_INT is 1, not 0.
It will not cause wrong results, but will cause slow operation.
It should be: 
#define JS_VALUE_IS_BOTH_INT(v1, v2) ((JS_VALUE_GET_TAG(v1) | JS_VALUE_GET_TAG(v2)) == 1)

**Comment by heroboy** [comment]
why close?
I have the same question.
