### ISSUE TITLE
File wildcards are not supported

### ISSUE THREAD

**Issue by lv-3** [bellard/quickjs#83]
Wildcards are not supported when calling the cp command.

```
let cpfile=["cp","-rf","/usr/local/include/quickjs/*.h", "./temp/"];
os.exec(cpfile);
```
result:
```
cp: cannot stat '/usr/local/include/quickjs/*.h': No such file or directory
```

The file actually exists, and there is no problem running directly in the terminal.

**Comment by samuel-obiedzinski** [comment]
Wildcards are supported by shell not by cp utility. quickjs has nothing to do with this.

`
let cpfile=["bash", "-c", '"cp -rf /usr/local/include/quickjs/*.h ./temp/"'];
os.exec(cpfile);
`

**Comment by lv-3** [comment]
Okay, got it
