### ISSUE TITLE
Any interest in a CMake configuration?

### ISSUE THREAD

**Issue by diamondman** [bellard/quickjs#88]
I have a good amount of CMake experience from rewriting most of the CMake configs at my office, and I would like to write a CMake config for quickjs. Among other features, a CMake config for quickjs that would export CMake and PackageConfig configurations (which allow developers to automate detecting quickjs) so people can easily integrate with quickjs.

I personally believe that the benefits added by using CMake could make it the CMake config would be the preferred way to use quickjs libraries (since CMake-config/PackageConfig support would make it easy for developers to link against quickjs no matter if installed through a package manager or built from source). Adding a CMake configuration would not mean the existing Makefile system would have to be removed, as both systems can coexist (though with some duplicated work when new files are added to the project). , but if no one 

It would be fun to write this configuration, but I would only want to do it if it is something the maintainer is interested in.

**Comment by lygstate** [comment]
Please take a look at https://github.com/lygstate/quickjs

**Comment by diamondman** [comment]
Ah, sorry I missed the message to go to the mailing list.
