### ISSUE TITLE
Get JS object from the opaque ID

### ISSUE THREAD

**Issue by projectitis** [bellard/quickjs#90]
Hi there,

I can see methods for getting an opaque ID based on the object JSValue - for example:
`void *JS_GetOpaque(JSValueConst obj, JSClassID class_id);`

But I don't see a way to retrieve the JSValue object based on the opaque ID:
`JSValue JS_GetObject(void *opaque);`

I would like to retrieve the JS Object from within the C++ object. The C++ object may or may not be bound to a JS object:
````
class Example {
public:
    void myMethod(){
        // Get JS object ID for this instance
        JSValue v = JS_GetObject( this );
        if (v) {
            // Do something with v
        }
    }
};
````

Cheers,
Peter

**Comment by bellard** [comment]
This is not possible. If you want to retrieve the associated JS object you have to store it in the opaque data.
