### ISSUE TITLE
Finalizers can't free quickjs resources on shutdown

### ISSUE THREAD

**Issue by mikezackles** [bellard/quickjs#92]
The problem scenario arises when native resources own quickjs resources (like promises or callbacks). The finalizers for the native resources are unable to destroy the quickjs resources at shutdown, meaning that by default the owned quickjs resources get leaked, which can generate a lot of noise during leak detection.

It is possible to work around this, but it is pretty painful: The application must keep track of the owned quickjs resources and destroy them *before* shutting down quickjs. But it must not destroy the native resources that quickjs owns, because quickjs will want to do so when it shuts down. This leads to a rather invasive pattern of destruction order interdependencies that in my experience is pretty easy to get wrong.

At least for me, it would greatly simplify things if finalizers could free quickjs resources at shutdown, meaning these workarounds would no longer be necessary.

**Comment by bellard** [comment]
I don't understand your problem. Finalizers can free (or more exactly decref) quickjs objects with JS_FreeValueRT() so there should be no leak in the end.
